
  kind: pipeline
  type: docker
  name: docker-build
  steps:

    - name: discord notification
      image: appleboy/drone-discord
      settings:
        webhook_id:
          from_secret: discord_webhook_id
        webhook_token:
          from_secret: discord_webhook_token
        message: @Nerds Test Notifications


    - name: publish
      image: plugins/docker
      settings:
        username: kevinbacon
        password: pa55word
        repo: foo/bar
        build_args:
          - HTTP_PROXY=http://yourproxy.com
      when:
        branch:
          - master
          - feature/*

