  kind: pipeline
  type: docker
  name: docker-build-publish
  node:
    location: glk
  steps:

    - name: docker build test on pr
      image: plugins/docker
      settings:
        username:
          from_secret: nexus_ci_user
        password:
          from_secret: nexus_ci_password
        password:
          from_secret: nexus_ci_password
        registry:
          from_secret: nexus_ci_docker_restricted
        repo: docker-restricted.buttahtoast.ch/${DRONE_REPO}
        tags:
          - ${DRONE_COMMIT_SHA}
        dockerfile: ${DOCKERFILE}
      when:
        event:
          - pull_request

    - name: docker build test on dev
      image: plugins/docker
      settings:
        username:
          from_secret: nexus_ci_user
        password:
          from_secret: nexus_ci_password
        password:
          from_secret: nexus_ci_password
        registry:
          from_secret: nexus_ci_docker_restricted
        repo: docker-restricted.buttahtoast.ch/${DRONE_REPO}
        tags:
          - ${DRONE_COMMIT_SHA}
        dockerfile: ${DOCKERFILE}
      when:
        branch:
          - feature/*
          - dev*
          - init
        event:
          - push

    - name: Docker Hub publsih on main
      image: plugins/docker
      settings:
        username:
          from_secret: dockerhub_user
        password:
          from_secret: dockerhub_password
        repo: ${DRONE_REPO}
        tags:
          - latest
        dockerfile: ${DOCKERFILE}
      when:
        branch:
          - main
          - master
        event:
          - push

    - name: Docker Hub publsih on tag
      image: plugins/docker
      settings:
        username:
          from_secret: dockerhub_user
        password:
          from_secret: dockerhub_password
        repo:  ${DRONE_REPO}
        tags:
          - ${VERSION_PREFIX}${DRONE_COMMIT_REF//refs\/tags\//}
          - latest
        dockerfile: ${DOCKERFILE}
      when:
        event:
          - tag

    - name: Docker Hub publsih README
      image:  jlesage/drone-push-readme
      settings:
        username:
          from_secret: dockerhub_user
        password:
          from_secret: dockerhub_password
        repo:  ${DRONE_REPO}
      when:
        event:
          - tag

  environment:
    VERSION_PREFIX:
    DOCKERFILE: ./Dockerfile
---
  kind: pipeline
  type: docker
  name: docker-audit
  node:
    location: glk
  steps:

    # - name: docker_build_check
    #   image: plugins/docker
    #   settings:
    #     username:
    #       from_secret: nexus_ci_user
    #     password:
    #       from_secret: nexus_ci_password
    #     repo: ${NEXUS_CI_DOCKER_RESTRICTED}/${DRONE_REPO}
    #     registry: ${NEXUS_CI_DOCKER_RESTRICTED}
    #     tags:
    #       - ${DRONE_COMMIT_SHA}
    #     dockerfile: ${DOCKERFILE}
    #   environment:
    #     DOCKERFILE: ./Dockerfile
    #     NEXUS_CI_DOCKER_RESTRICTED:
    #       from_secret: nexus_ci_docker_restricted
    #   when:
    #     event:
    #       - pull_request
    #       - push
    - name: docker_build_check
      image: docker
      commands:
        - docker build . -f $${DOCKERFILE} -t $${DRONE_COMMIT_SHA}
      volumes:
        - name: docker
          path: /var/run/docker.sock
      environment:
        DOCKERFILE: ./Dockerfile

    - name: Docker Audit
      image: goodwithtech/dockle
      commands:
        - dockle --exit-code 1 --exit-level fatal $${DRONE_COMMIT_SHA}
      volumes:
        - name: docker
          path: /var/run/docker.sock
      when:
        event:
          - pull_request
          - push
      depends_on: [ docker_build_check ]
  volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
