
  kind: pipeline
  type: docker
  name: docker-build
  steps:

    - name: Docker Hub publsih on master
      image: plugins/docker
      settings:
        username:
          from_secret: dockerhub_user
        password:
          from_secret: dockerhub_password
        repo: {{ DRONE_REPO }}
        tags:
          - latest
        dockerfile: {{ DOCKERFILE }}
      environment:
        DOCKERFILE: DOCKERFILE
      when:
        event:
          - tag

    - name: Docker Hub publsih on tag
      image: plugins/docker
      settings:
        username:
          from_secret: dockerhub_user
        password:
          from_secret: dockerhub_password
        repo: {{ DRONE_REPO }}
        tags:
          - {{ DRONE_COMMIT_REF | regex_search(''^(?<=refs\/tags\/).*$') }}
          - latest
        dockerfile: {{ DOCKERFILE }}
      environment:
        DOCKERFILE: DOCKERFILE
      when:
        event:
          - tag

    - name: discord notification
      image: appleboy/drone-discord
      settings:
        webhook_id:
          from_secret: discord_webhook_id
        webhook_token:
          from_secret: discord_webhook_token
        message: @Nerds Docker build for {{ DRONE_REPO }} {{ build.status}} // Infos {{build.number}} {{build.link}}"
      when:
        status: [ success, failure ]
