
  kind: pipeline
  type: docker
  name: docker-build
  steps:

    - name: Docker Hub publsih on dev
      image: plugins/docker
      settings:
        username:
          from_secret: dockerhub_user
        password:
          from_secret: dockerhub_password
        repo: $${DRONE_REPO}
        tags:
          - dev-{{ DRONE_COMMIT_REF | regex_search(''^(?<=refs\/heads\/).*$') }}
        dockerfile: {{ DOCKERFILE }}
      environment:
        DOCKERFILE: DOCKERFILE
      when:
        branch:
          - feature/*
          - dev*
          - init

    - name: Docker Hub publsih on master
      image: plugins/docker
      settings:
        username:
          from_secret: dockerhub_user
        password:
          from_secret: dockerhub_password
        repo: {{ DRONE_REPO }}
        tags:
          - latest
        dockerfile: {{ DOCKERFILE }}
      environment:
        DOCKERFILE: DOCKERFILE
      when:
        event:
          - tag

    - name: Docker Hub publsih on tag
      image: plugins/docker
      settings:
        username:
          from_secret: dockerhub_user
        password:
          from_secret: dockerhub_password
        repo: ${DRONE_REPO}
        tags:
          - prod-{{ DRONE_COMMIT_REF | regex_search('^(?<=refs\/tags\/).*$') }}
          - latest
        dockerfile: {{ DOCKERFILE }}
      environment:
        DOCKERFILE: DOCKERFILE
      when:
        event:
          - tag
